---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - API_KEY=sc_xZim9nwtY7lTQSXlscnSjQ
  - API_URL=https://api.simplecast.com/v1
  - GA_ID=UA-113075532-4
  - GRIDSOME_ROOT_URL=https://dnc.show
  - PODCAST_ID=1386
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
